tests/apps_test.go, tests/builds_test.go, tests/perms_test.go, tests/users_test.go
This fixes several tests which broke when DRF was updated in https://github.com/deis/workflow/commit/90b02356f9fe7cb49f6f6300892d61edf4cf6fbc.
=> chore(tests): update for new Django REST framework

tests/apps_test.go
Fixes two broken test cases in apps_test.go.
=> fix(tests): clean up .git and fix config:list syntax

tests/apps_test.go
=> feat(apps_test): add further apps:info expectations

_scripts/deploy.sh
As part of the effort towards the promotion of immutable component images...
=> feat(deploy.sh): remove hardcoded VERSION to use git-<sha> declared in Makefile

tests/apps_test.go, tests/perms_test.go, tests/tests_suite_test.go
Also created reusable `deployApp` func to be used among multiple tests
=> feat(perms_test): add perms:* invocations on deployed app

jobs/workflow_e2e_pr.groovy
This job, as mentioned in job description, builds and pushes the
Docker image for workflow-e2e, kicking off the e2e test job on success.
=> feat(jenkins): add DSL for the workflow-e2e-pr job

tests/domains_test.go
Requires https://github.com/deis/workflow/pull/473
=> fix(domains_test): app domain is created when an app is created

tests/version_test.go
=> fix(version_test): version now includes 7-character git sha

tests/domains_test.go
Properly tested
```
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 3 of 72 Specs in 81.887 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 69 Skipped PASS
```
=> fix(domains_test): actually test add output

tests/apps_test.go, tests/builds_test.go, tests/releases_test.go, tests/tests_suite_test.go
=> feat(builds_tests): add deis builds command tests

tests/releases_test.go
=> feat(releases_test): finish implementing releases test

tests/limits_test.go
=> feat(tests): add limits tests

tests/apps_test.go, tests/builds_test.go, tests/config_test.go, tests/domains_test.go, tests/limits_test.go, tests/perms_test.go, tests/ps_test.go, tests/tests_suite_test.go
Add test to test the deployment of the custom buildpack app and separate the create and deploy functions so that apps can be created in multiple ways(like using buildpacks).
=> feat(app_test): add test to deploy a custom buildpack app

Makefile
=> fix(Dockerfile): pass same options to test binary

tests/builds_test.go, tests/domains_test.go, tests/releases_test.go, tests/tests_suite_test.go
=> fix(createApp): move Say checks to createApp, depending on gitRemote bool

README.md
Ref https://github.com/deis/deis/issues/4962
=> doc(README.md): update the Readme to reflect beta status

tests/certs_test.go
=> feat(certs_test): cover scenario described in https://github.com/deis/workflow/pull/492

.travis.yml
=> feat(.travis.yml): add docker-build step for ci build command

tests/domains_test.go
=> feat(domains_test): increase domains curl cmd timeout to 15 seconds

tests/builds_test.go, tests/ps_test.go
In the process, created listProcs utility function in ps_test for re-use in any test
Depends on https://github.com/deis/controller/pull/497
cc @helgi
=> feat(builds/ps_test): add a few more checks to build_test scenarios, cleanup beforeEach

tests/builds_test.go, tests/releases_test.go
Previously we were rolling back to v1 which isn't a legit build+config/12-factor
release. cc @bacongobbler @mboersma 
Closes https://github.com/deis/controller/issues/538
=> fix(releases_test): rollback to actual build+config release in test

tests/tests_suite_test.go
see sgoings/chart-mate#28 and deis/charts#186
=> ref(tests): write junit.xml to $HOME/junit.xml

tests/tests_suite_test.go
http://nip.io/
uses power DNS backend hopefully solves dns failures
=> feat(dns): change xip to nip

tests/builds_test.go, tests/config_test.go, tests/ps_test.go
Also updated some expectations to look for 503 (including still pending)
on account of https://github.com/deis/router/pull/153
=> feat(tests): reenable tests addressed by deis/controller #557

tests/tests_suite_test.go
=> fix: Make the junit reporter handle running the tests in parallel

.travis.yml
=> fix(ci): Dockerize bootstrap during Travis build

tests/releases_test.go
Depends on https://github.com/deis/controller/pull/637
=> fix(release): move from UTC to Z to comply with ISO8601

tests/ps_test.go
deis/controller#631 has been fixed now
=> fix(ps): re-enable ps:restart one tests

Dockerfile, tests/registry_test.go
This depends on the following PRs:
* https://github.com/deis/jenkins-jobs/pull/63
* https://github.com/deis/controller/pull/653
* https://github.com/deis/workflow-cli/pull/45
=> feat(registry): add tests for private registry functionality

tests/cmd/git/commands.go, tests/git_push_test.go
=> feat(git_push_test): curl app endpoint for "Powered by"

Makefile
FOCUS_TEST="deis ps" will allow you run a specific set of tests in the test suite
Allows for the following command - 
```GINKGO_NODES=4 DEIS_CONTROLLER_URL=http://deis.domain.com FOCUS_TEST="deis ps" make test-integration```
=> chore(makefile): Add the ability to focus a test

Dockerfile, tests/cmd/apps/commands.go
Complements deis/workflow-cli#57
=> chore(apps:create): Assert on new/improved CLI output

tests/builds_test.go
https://github.com/deis/controller/pull/665
=> feat(deploy): test that setting DEPLOY_BATCHES on an app works

tests/apps_test.go
This covers some commands that caused problems in the past.
~~This also necessarily includes the change from #211. I will rebase it after that merges.~~ Rebased.
Requires deis/controller#751.
Closes #204.
=> test(apps_test): add more specs for "deis run"

Dockerfile, tests/apps_test.go
=> chore(Dockerfile): update Workflow CLI to latest published

Dockerfile
=> chore(Dockerfile): update deis CLI to a17f89a

README.md
Ref https://github.com/deis/workflow/issues/285
=> docs(README.md): remove beta status

tests/registry_test.go
Compliments https://github.com/deis/controller/pull/791
=> feat(registry): PORT is required for private registry

tests/apps_test.go
=> fix(apps_test): escape quotes properly in deis run spec

tests/limits_test.go, tests/registry_test.go, tests/tags_test.go
Requires https://github.com/deis/controller/pull/826
=> fix(config): unsetting a key that does not exist results in exit 1

tests/deployments_dockerfiles_test.go, tests/deployments_git_push_test.go, tests/deployments_ps_test.go, tests/dockerfiles_test.go, tests/git_push_test.go, tests/ps_test.go
fixes https://github.com/deis/workflow-e2e/issues/208
=> feat(procfile): add support to test dockerfile app with proctype WEB

tests/apps_test.go
=> fix(app): DRF 3.4.1 changed the way it does certain errors

tests/buildprocfile_test.go
=> feat(skip): make procfile test pending

tests/buildprocfile_test.go
Previously the test is not waiting for the commands to finish execution add exit(o) gomega function to wait for the command to finish executing 
closes https://github.com/deis/workflow-e2e/issues/299
=> feat(procfile): unskip builds procfile test

tests/maintenance_test.go
ref https://github.com/deis/workflow-cli/pull/171
=> feat(maintenance): Add test for maintenance mode

tests/healthcheck_test.go, tests/registry_test.go
with this PR https://github.com/deis/controller/pull/1036 the healthchecks are properly checked and hence the e2e fails.
=> fix(healthcheck): use correct port the image exposes

docker-test-integration.sh
Ref https://github.com/deis/workflow-cli/pull/218
Ref https://github.com/deis/jenkins-jobs/pull/230
=> feat(docker-test-integration.sh): check if 'stable'

tests/git_push_test.go
Ref https://github.com/deis/workflow-e2e/issues/329
Ref https://github.com/deis/controller/issues/1106
=> fix(tests/git_push_test.go): bump deis run timeout

tests/apps_test.go
this is for https://github.com/deis/logger/pull/123
=> chore(apps_test): Fix up logger tests for new log format

tests/labels_test.go
Add new Label command.
Labels are general key value string to each app just for administration purpose.
See https://github.com/deis/workflow/issues/597
=> feat(label-cmd): add Label cmd

tests/labels_test.go
requires workflow-cli#275
requires controller-sdk-go#107
=> fix(tests/labels_test.go): adjust spacing

tests/apps_test.go, tests/builds_test.go, tests/certs_test.go, tests/cmd/apps/commands.go, tests/cmd/certs/commands.go, tests/cmd/domains/commands.go, tests/domains_test.go
Requires controller-sdk-go#113
Ref https://github.com/deis/controller-sdk-go/pull/113
=> ref(*): adjust error message expectations

tests/limits_test.go
Accept new cli format limits:set web=500m/2000m
Value is map to requests/limits parameter in Kubernetes resource management.
See https://github.com/deis/workflow/issues/562
=> feat(limits-cmd): accept new limits:set value type

tests/git_push_test.go
This can be used to test fix for https://github.com/deis/builder/issues/490 -- unless unit coverage is possible/acceptable (ci will fail until fix is in)
=> feat(tests): add config:set spec with dockerfile app

tests/apps_test.go, tests/auth_test.go, tests/buildpacks_test.go, tests/buildprocfile_test.go, tests/builds_test.go, tests/certs_test.go, tests/cmd/auth/commands.go, tests/config_test.go, tests/dockerfiles_test.go, tests/domains_test.go, tests/git_push_test.go, tests/healthcheck_test.go, tests/keys_test.go, tests/labels_test.go, tests/limits_test.go, tests/maintenance_test.go, tests/perms_test.go, tests/ps_test.go, tests/registry_test.go, tests/releases_test.go, tests/routing_test.go, tests/tags_test.go, tests/tls_test.go, tests/users_test.go, tests/whitelist_test.go
Ref https://github.com/deis/workflow-e2e/issues/350
Closes https://github.com/deis/workflow-e2e/issues/350
=> ref(tests): update tests for new registration mode default

tests/cmd/auth/commands.go
We appear to be getting bitten by an intermittent error in a dependency for the `gexpect` library -- we only use it for the one interactive registration bit of code, and I believe we would rather relegate this testing to manual interaction rather than struggle with the quirks of this library...
for example, from https://ci.deis.io/job/workflow-chart-e2e/1042/console
```
15:03:08 [BeforeSuite] BeforeSuite 
15:03:08 /go/src/github.com/deis/workflow-e2e/tests/tests_suite_test.go:96
15:03:08 
15:03:08   Expected error:
15:03:08       <*os.PathError | 0xc4201807e0>: {Op: "read", Path: "/dev/ptmx", Err: 0x5}
15:03:08       read /dev/ptmx: input/output error
15:03:08   not to have occurred
15:03:08 
15:03:08   /go/src/github.com/deis/workflow-e2e/tests/cmd/auth/commands.go:35
```
=> fix(tests/auth): no interactive register for admin

Makefile
=> feat(Makefile): add test target
