deis/workflow-e2e

Dockerfile
Makefile
glide.lock
glide.yaml
tests/tests_suite_test.go

Also add glide files for dependency management. With this patch, you can run `make docker-build docker-test-integration` to build and run the tests in a docker container.
Fixes #1 
Fixes deis/workflow#193
Fixes deis/workflow#139
Replaces deis/workflow#194
Note: we should make this public before merging, as it closes issues in deis/workflow, a public repository.

fix(Dockerfile,Makefile,glide.yaml,glide.lock): dockerize the dev and test environment

---

tests/apps_test.go
tests/auth_test.go
tests/builds_test.go
tests/cmd_test.go
tests/config_test.go
tests/domains_test.go
tests/healthcheck_test.go
tests/help_test.go
tests/keys_test.go
tests/limits_test.go
tests/package.go
tests/perms_test.go
tests/ps_test.go
tests/releases_test.go
tests/tags_test.go
tests/tests_suite_test.go
tests/users_test.go
tests/version_test.go

so that golint doesn’t complain about underscores in package names

fix(tests): change package names

---

_scripts/deploy.sh

Changes the repository org to `deisci` for consistency with the other images that are pushed for Deis v2.

fix(deploy.sh): push docker images to deisci/ orgs

---

Makefile
tests/apps_test.go
tests/config_test.go
tests/healthcheck_test.go
tests/tests_suite_test.go

This gets four additional cases passing and disables some problematic tests for now. All enabled tests should be expected to pass after this, so we can build incrementally on this base and ensure things stay green. :green_heart:

fix(tests): get subset of integration tests passing

---

tests/tests_suite_test.go

Only the command stdeout/stderr was being printed, which was difficult to decipher without the relevant command. 
Before:
```console
Logged in as test-81
=== Apps
test-238696780
test-435805123
test-755573488
Destroying test-238696780...
done in 0s
```
After:
```console
$ deis login http://deis.192.168.64.2.xip.io:32762 --username=test-81 --password=asdf1234
Logged in as test-81
$ deis apps
=== Apps
test-238696780
test-435805123
test-755573488
$ deis destroy --app=test-238696780 --confirm=test-238696780
Destroying test-238696780...
done in 0s
```
Prints to `GinkoWriter` so everything will be silent unless a test case fails or the `-ginkgo.v` flag is given (which it is in `make test-integration`).

fix(start): echo command line

---

tests/tests_suite_test.go

Avoids a 409 error and improves repeatability of the suite. See deis/workflow#391.

fix(cancel): delete apps before auth:cancel

---

tests/apps_test.go

This fixes a test that was broken by changes to deis/workflow. The current format is:
```console
$ deis info -a test-726978103
=== test-726978103 Application
updated:  2016-02-21T00:43:22UTC
uuid:     9cd804db-dc5a-47e4-ad3c-f0a23894d92b
created:  2016-02-21T00:43:09UTC
url:      test-726978103.192.168.64.2.xip.io:31560
owner:    test-81
id:       test-726978103
=== test-726978103 Processes
--- web:
test-726978103-v2-web-uriur up (v2)
=== test-726978103 Domains
test-726978103
```

fix(apps_test): update apps:info expectations

---

tests/apps_test.go
tests/ps_test.go

Uses ginkgo's [table-driven-tests](http://onsi.github.io/ginkgo/#extensions) extension to test likely `ps:scale` and `ps:restart` scenarios.
Closes #17.
TODO:

feat(ps_test): implement table-driven processes tests

---

tests/ps_test.go

The default of 2 minutes was sometimes not long enough for the `ps:scale` or `ps:restart` operation to complete. I've tested with a 5 minute timeout and not seen those failures recur.

fix(ps_test): increase scale and restart timeouts to 5 min

---

tests/apps_test.go
tests/keys_test.go

apps:logs relies on https://github.com/sgoings/chart-mate/pull/2 so that is still blocked.

feat(tests): add apps:transfer, apps:run

---

tests/ps_test.go

some cases may cause the return value of scrapeProcs (the return value
of which is assigned to beforeProcs) to have no processes). This commit
ensures that there’s at least 1 returned process, or the test fails
Fixes #63

fix(tests/ps_test.go): fix Intn panic

---

tests/tests_suite_test.go

A debug check is not necessary, since the `GingkgoWriter` itself decides whether to print based on `go test` flags.

fix(tests_suite): print commands again

---

.gitignore

The .gitignore file had many old entries from its past in Deis v1, and the example-go app had been checked in under `tests/`--mistakenly, I assume.

ref(.gitignore): purge example app and clean up

---

Makefile

These changes make it possible for us to deploy two docker containers via the Travis job:
- git sha based tag (what we've had for a week or so)
- canary type tag (allows ci system to *always use the latest tests* on runs)

feat(Makefile): produce git sha based and canary type docker image tags

---

Makefile

Ginkgo's default of 5 seconds is unreasonable for e2e tests. The frequent warnings about "slow test" are not helpful in this context.
Closes #79.

fix(Makefile): increase "slow test" warning to 2 min

---

tests/config_test.go

~~Still need to write the `deis config:pull` and `config:push` tests, but I put this out here now in case I don't get back to it today.~~
~~Blocked by deis/workflow#460.~~
See deis/workflow#478 for an explanation of one spec marked Pending.

fix(config_test.go): restore config command tests

---

tests/config_test.go

Now that deis/workflow#480 is merged, this test also passes:
```console
$ DEIS_ROUTER_SERVICE_HOST=192.168.64.2 DEIS_ROUTER_SERVICE_PORT=31759 make test-integration
...
$ deis run -a test-108788304 env
Running 'env'...
HOSTNAME=test-108788304-v3-run-1
KUBERNETES_PORT=tcp://10.100.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
FOO=讲台
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.100.0.1
TEST_108788304_PORT_80_TCP_PROTO=tcp
TEST_108788304_PORT_80_TCP_ADDR=10.100.228.98
TEST_108788304_SERVICE_PORT=80
DOCKERIMAGE=1
TEST_108788304_PORT=tcp://10.100.228.98:80
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/bin
TEST_108788304_SERVICE_HOST=10.100.228.98
PWD=/app
TEST_108788304_SERVICE_PORT_HTTP=80
GOMAXPROCS=1
HOME=/app
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp …
```

fix(tests): enable the non-ascii config:set test

---

Makefile

Now that the e2e tests are more fleshed out, they routinely take longer than `go test`'s default of 10 minutes.
cc:@vdice

fix(Makefile): increase overall test timeout to 60 min

---

tests/tags_test.go

~~Still a couple of `// TODO`s and a 500 error to investigate.~~
~~I think deis-workflow's validation on labels (tags) needs to be improved to match https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/labels.md#syntax-and-character-set. Currently we don't allow `deis tags:set myprefix/mytag=myvalue` because we disallow a slash `/` in the tag name.~~ Fixed in #481.
Closes #18.

feat(tags_tests.go): implement tags-related tests

---

tests/tests_suite_test.go

In CI we have seen at least [one case](https://ci.deis.io/job/deis-v2-e2e/962/console) where the default `Eventually` timeout of 10 seconds was not enough for a `deis destroy` operation, which isn't surprising. This bumps that up to `defaultMaxTimeout` (5 minutes).

fix(destroyApp): allow max timeout for "deis destroy"

---

.travis.yml
Dockerfile
Makefile
tests/admin_test.go
tests/apps_test.go
tests/auth_test.go
tests/builds_test.go
tests/certs_test.go
tests/config_test.go
tests/domains_test.go
tests/healthcheck_test.go
tests/help_test.go
tests/keys_test.go
tests/limits_test.go
tests/perms_test.go
tests/ps_test.go
tests/releases_test.go
tests/tags_test.go
tests/tests_suite_test.go
tests/users_test.go

This PR gives us the ability to run the e2e test suite in parallel. This dramatically speeds up the test run making it easier on the end user who is trying to get a crucial change. For example here is a sequential test run performed against my 4 node m4.xlarge cluster -
```
Ran 100 of 113 Specs in 2003.951 seconds
SUCCESS! -- 100 Passed | 0 Failed | 13 Pending | 0 Skipped PASS
```
That test run took almost 33 minutes to complete.
But when running the tests in parallel we can see results like the following:
```
Ran 100 of 113 Specs in 367.949 seconds
SUCCESS! -- 100 Passed | 0 Failed | 13 Pending | 0 Skipped
```
That is just over 6 minutes.
To accomplish this several changes were made to the test suite:
1. Use http to register and login all users. This allows us to store the login token in …

feature: Run the e2e test suite in parallel

---

apps/delete.go
apps/set.go
tests/tests_suite_test.go

this set will be used to track installed apps, so that the tests can delete all corresponding namespaces after all are finished
This PR was inspired from the discussion at https://github.com/deis/workflow-e2e/issues/142#issuecomment-204458448
Note that this still needs manual testing to ensure that app namespaces are properly cleaned up.

feat(apps): track created apps and delete their namespaces after all tests are done

---

tests/tests_suite_test.go

… that was being used to wait for SSH key propagation (which no longer
should happen)
Fixes https://github.com/deis/workflow-e2e/issues/139

fix(tests_suite_test.go): remove sleep

---

tests/tags_test.go

Example output is:
```
map[failure-domain.beta.kubernetes.io/region:us-central1 failure-domain.beta.kubernetes.io/zone:us-central1-b kubernetes.io/hostname:gke-helm-testing-64fa-747f4ea5-node-ctnu beta.kubernetes.io/instance-type:n1-standard-4 cloud.google.com/gke-nodepool:default-pool]
```
without - in regex then `failure-` was never matched (https://www.debuggex.com/r/9sqOvZrKzMc0zadY) but with it that would be included (https://www.debuggex.com/r/Yj_XRnGHtHW29JCl)

fix(tags): regex for tags did not include - in names

---

README.md

Link to canonical Deis chart installation guide at https://github.com/deis/charts#installation instead of managing separate instructions here, which are prone to diverge.

docs(README): link to canonical Deis chart installation guide

---

tests/cmd/builds/commands.go

I'm noticing some failures that look like this:
```
23:25:00 $ deis auth:register http://deis.10.83.252.114.nip.io --username=test-91253 --password=asdf1234 --email=test-91253@deis.io
23:25:00 Registered test-91253
23:25:00 Logged in as test-91253
23:25:00 $ deis apps:create test-129088529 --no-remote
23:25:00 Creating Application... ...done, created test-129088529
23:25:00 remote available at ssh://git@deis.10.83.252.114.nip.io:2222/test-129088529.git
23:25:00 $ deis builds:create --app=test-129088529 deis/example-dockerfile-http
23:25:00 Creating build... ...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o...o. …
```

fix(*): Use max timeout waiting for build:create to exit

---

Dockerfile

Fixes #172 
Low hanging, late Friday fruit...
This creates a substantially smaller e2e image.  It uses Alpine.  Experience shows this would not be good for a general purpose Go development environment, but for this focused use, it seems perfectly fine.
Tests pass:
```
[kent@mbp workflow-e2e]$ make docker-test-integration
docker run --rm -e GINKGO_NODES=15 -e DEIS_CONTROLLER_URL=http://deis.krancour.deis.ninja -e DEFAULT_EVENTUALLY_TIMEOUT= -e MAX_EVENTUALLY_TIMEOUT= -e JUNIT= -e DEBUG= -v /Users/kent/.kube:/root/.kube -w /go/src/github.com/deis/workflow-e2e 192.168.99.100:5000/krancour/workflow-e2e:git-9139411 make test-integration
fatal: Not a git repository (or any of the parent directories): .git
ginkgo -slowSpecThreshold=120.00 -noisyPendings=false -nodes=15 tests/
Running Suite: Deis …
```

ref(Dockerfile): Base the image on Alpine-- much smaller

---

tests/git_push_test.go

Adds a ginkgo test spec covering a Dockerfile-based `git push` and `curl`. In conjunction with the existing `deis pull` app tests, this should ensure basic e2e test coverage of all three app deployment flavors.
This is slightly repetitive, and I plan to revisit that when implementing #47.
Closes #45.

tests(git_push): add explicit buildpack & dockerfile tests

---

tests/apps_test.go

deis run can take as long to boot as any other app

fix(apps): extend the time deis run is allowed to run

---

Makefile
tests/buildpacks_test.go
tests/cmd/git/commands.go
tests/dockerfiles_test.go
tests/git_push_test.go

This adds specs that cover deploying all the deis/example-* apps. These can take a while to run, so they are disabled by default. You can run *only* these tests by providing a bogus match to the new `$SKIP_TEST` var and a correct regex to `$FOCUS_TEST`:
```console
$ SKIP_TEST=none FOCUS_TEST='all (buildpack|dockerfile) apps' make test-integration
ginkgo -slowSpecThreshold=120.00 -noisyPendings=false -p --skip="none" --focus="all (buildpack|dockerfile) apps" tests/
Running Suite: Deis Workflow
============================
Random Seed: 1462228973
Will run 14 of 170 specs
...
```
See also #179 for the introduction of `$FOCUS_TEST`.
TODO:

tests(*): add specs for all buildpack & dockerfile example apps

---

tests/registry_test.go

I pulled out the failure scenario since I couldn't for the life of me get it to pass
In case anyone want to give it a go then this was the basis for it. Before I had some additional `Eventually` checks in there but I just think what we have right now is not setup for the way the CLI is failing
```go
Specify("that user can not deploy from a private registry using registry credentials without a port", func() {
// read-only access
registry_creds := "TP5BS3NHW0OZ20GER4IORTIJF90J48KKJ8NX8YC7Z22N5P7WE27BRKVMQ4QAEID8"
sess, err := cmd.Start("deis registry:set --app=%s username=deisci+e2e_registry password=%s", &user, app.Name, registry_creds)
Eventually(sess, settings.MaxEventuallyTimeout).Should(Say("PORT needs to be set in the config when using a private registry")) …
```

fix(registry): more port setting and fix up error message detection

---

tests/cmd/apps/commands.go

When I run e2e tests locally, one spec always fails when doing `deis open` because the expected URL argument differs slightly:
```go
$ FOCUS_TEST="that user can open that app" DEIS_CONTROLLER_URL=deis.deis.rocks make test-integration
...
• Failure [42.114 seconds]
deis apps
/Users/matt/Projects/src/github.com/deis/workflow-e2e/tests/apps_test.go:232
with an existing user
/Users/matt/Projects/src/github.com/deis/workflow-e2e/tests/apps_test.go:230
who owns an existing app that has already been deployed
/Users/matt/Projects/src/github.com/deis/workflow-e2e/tests/apps_test.go:228
that user can open that app [It]
/Users/matt/Projects/src/github.com/deis/workflow-e2e/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:354
Expected
<string>: http://test-1760863.deis.rocks
to equal
<string>: …
```

fix(apps/commands): match substring, not entire string

---

tests/cmd/git/commands.go
tests/cmd/helper.go
tests/git_push_test.go
tests/model/model.go

~~Still some TODOs to address that I can move forward with if it sounds like this will still be wanted after~~ ~~Still need to align with work done in https://github.com/deis/workflow-e2e/pull/235~~
Adds spec for https://github.com/deis/builder/pull/369
cc @mboersma

feat(git_push_test.go): add git push interrupt test

---

tests/cmd/git/commands.go
tests/git_push_test.go

```console
$ FOCUS_TEST="git push deis master" DEIS_CONTROLLER_URL=your.workflow.host make test-integration
...
Ran 6 of 179 Specs in 364.039 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 173 Skipped 
```
(Add `-v` in the Makefile `TEST_OPTS` to see hilariously interleaved buildpack/dockerfile output.)
Refs #224.
cc: @vdice.
TODO:

test(git_push): add concurrent push specs

---

tests/git_push_test.go

Adds a ginkgo test spec to ensure that `git push` of a broken Dockerfile fails predictably.
Refs #85, deis/dockerbuilder#74, deis/workflow-e2e#185.
TODO:

feat(git_push_test): add broken Dockerfile spec

---

tests/builds_test.go

Validates that `deis pull` of a nonexistent image fails in a predictable way.

feat(builds_test): add nonexistent docker image spec

---

tests/builds_test.go

The specific error message varies between Kubernetes 1.2.5 and 1.3.0 and probably also on the underlying Docker version. I upgraded my GKE cluster and found that this spec breaks because 1.2.5 mentioned `deis/nonexistent:dummy` and 1.3.0 mentions `deis/nonexistent` (no tag).

fix(builds_test): relax matches for bad docker image specs

---

tests/cmd/configs/commands.go
tests/deployments_buildpacks_test.go
tests/deployments_builds_test.go
tests/deployments_config_test.go
tests/deployments_dockerfiles_test.go
tests/deployments_git_push_test.go
tests/deployments_healthcheck_test.go
tests/deployments_ps_test.go
tests/deployments_releases_test.go

Should be eventually removed
Requires deis/controller#854
Adds a `config:set` cmd that allows us to set `DEIS_KUBERNETES_DEPLOYMENTS=1` as needed

feat(deployments): split out tests for deployment specific tests

---

tests/deployments_git_push_test.go
tests/git_push_test.go

Adds a ginkgo test spec to ensure that `git push` with a bad buildpack fails predictably. Thanks to @bacongobbler for creating the epic-fail buildpack that makes this easy.
Closes #185.
TODO:

feat(git_push_test): add "bad buildpack" test spec

---

docker-test-integration.sh

It appears `CLI_VERSION` other than `latest` was not being used,
due to the `-ne` check.  Also added `-f` flag to `curl` command
to echo failures and exit non-zero if the url is not valid, etc.
Closes https://github.com/deis/workflow-e2e/issues/256
Requires https://github.com/deis/jenkins-jobs/pull/147
Requires https://github.com/deis/charts/pull/306

fix(docker-test-integration.sh): actually override CLI_VERSION

---

Makefile

~~In particular, updates controller-sdk-go to the current tip of master.~~

chore(Makefile): use latest go-dev and glide

---

tests/certs_test.go

https://github.com/tomchristie/django-rest-framework/pull/4194
Requires deis/controller#892

fix(certs): limit=0 is invalid in DRF 3.4

---

Makefile

Wrapping in quotes to ensure a multi-word focus is used properly:
w/o this fix (all specs run -- we currently have a subset marked pending):
```
$ FOCUS_TEST="deis config" make docker-test-integration
docker run --rm -e GINKGO_NODES=15 -e SKIP_OPTS=--skip="all (buildpack|dockerfile) apps" -e FOCUS_OPTS=--focus="deis config" -e DEIS_CONTROLLER_URL= -e DEIS_ROUTER_SERVICE_HOST=146.148.64.213 -e DEIS_ROUTER_SERVICE_PORT=80 -e DEFAULT_EVENTUALLY_TIMEOUT= -e MAX_EVENTUALLY_TIMEOUT= -e JUNIT= -e DEBUG= -e CLI_VERSION=latest -v /Users/vaughndice/.kube:/root/.kube -w /go/src/github.com/deis/workflow-e2e quay.io/vdice/workflow-e2e:git-81d2b38 ./docker-test-integration.sh
Installing Workflow CLI version 'latest' via url 'https://storage.googleapis.com/workflow-cli/deis-latest-linux-amd64'
% Total …
```

fix(Makefile): wrap FOCUS_TEST in quotes

---

Makefile
tests/buildprocfile_test.go

test to check builds with a different procfile
refer https://github.com/deis/workflow-e2e/issues/202
flow of steps 
```
$ deis pull deis/example-dockerfile-http -a test1
Creating build... done
smothikis-MacBook-Pro:deis smothiki$ deis apps:info -a test1
=== test1 Application
updated:  2016-07-27T22:23:56Z
uuid:     8c72de40-c9b9-4322-ab58-b6b771ad45e0
created:  2016-07-27T22:23:25Z
url:      test1.104.154.49.56.nip.io
owner:    sm
id:       test1
=== test1 Processes
--- cmd:
test1-v2-cmd-q6o7a up (v2)
=== test1 Domains
test1
smothikis-MacBook-Pro:deis smothiki$ kubectl get pods --namespace=test1
NAME                 READY     STATUS    RESTARTS   AGE
test1-v2-cmd-q6o7a   1/1       Running   0          4m
(reverse-i-search)`deis ': deis apps:info -a test1
smothikis-MacBook-Pro:deis …
```

feat(procfile): create a build with a procfile

---

docker-test-integration.sh

Also run chmod as a separate command as conditionals negate exit on error that -e is trying to provide
This should prevent the CI system form continuing when there is a problem downloading the CLI and also should let GCS settle down a bit after the binary is uploaded by providing the retry and some preprive (10 seconds) between each retry

fix(Makefile): add retrying to workflow CLI download

---

Makefile
docker-test-integration.sh

Now that we have separate `-pr` and `-master` buckets that could feasibly
contain a given cli binary.
Ref https://github.com/deis/workflow-cli/pull/190

feat(docker-test-integration.sh): try curling cli from multiple buckets

---

Makefile
glide.lock

Updates docker-go-dev and three core e2e vendored packages to their latest commits.

chore(glide.lock): update ginkgo, gomega, controller-sdk-go

---

docker-test-integration.sh

Credit to @jchauncey for finding the issue.  (When CLI_VERSION is set to a release version, we were unable to find/dl the binary as we were not checking the release bucket.)

fix(docker-test-integration.sh): check workflow-cli-release bucket, too.

---

docker-test-integration.sh

Must be set to `true` to enable DEBUG_MODE.  
The default in the [chart](https://github.com/deis/workflow-e2e/blob/master/charts/workflow-e2e/values.yaml#L8) is `false`, which paired with previous logic simply checking if non-empty, meant debug mode was being run when not intended.

fix(docker-test-integration.sh): explicit DEBUG_MODE check

---

glide.lock
glide.yaml
tests/auth_test.go

The caveat here is the _semi-interactive_ compromise.  I could not get interactive password entry (and re-entry for confirmation) to work -- the cli always claimed the passwords did not match.  After an initial dive/experimentation into the `gexpect` library code we use here, I determined quite a bit of effort would be needed to shape up the code to begin to debug... 
Therefore, I believe our bases are still covered (in checking behavior after an interactive register -- albiet only with username and email here).  I can file a follow-up issue to revisit the aforementioned conundrum, if that is deemed necessary.

feat(auth_test.go): add interactive register spec
